inflation_layer:
  enabled: true
  inflation_radius: 1.0
  cost_scaling_factor: 20

pointcloud_layer:
  enabled: true
  max_obstacle_height: 0.60  
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  obstacle_range: 3.0
  raytrace_range: 3.0
  publish_voxel_map: true
  observation_sources: scan
  scan: 
    data_type: PointCloud
    topic: /svea7/viz_lidar_points
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.6

global_frame: map
robot_base_frame: svea7/base_link
update_frequency: 5.0
publish_frequency: 2.0
rolling_window: true
width: 4.0
height: 4.0
resolution: 0.05
robot_radius: 0.25
plugins:    
    - {name: pointcloud_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

